export const ACTIONS = {
  // WS
  WS_CONNECTION_START: 'WS_CONNECTION_START',
  WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS',
  WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR',
  WS_GET_MESSAGE: 'WS_GET_MESSAGE',
  WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED',
  WS_CONNECTION_CLOSE: 'WS_CONNECTION_CLOSE',
  WS_SEND_MESSAGE: 'WS_SEND_MESSAGE',
};
