export const WS_CONNECTION_START_USER = 'WS_CONNECTION_START_USER';
export const WS_CONNECTION_START_ALL = 'WS_CONNECTION_START_ALL';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED_ALL = 'WS_CONNECTION_CLOSED_ALL';
export const WS_CONNECTION_CLOSED_USER = 'WS_CONNECTION_CLOSED_ALL_USER';
export const WS_GET_MESSAGE = 'WS_GET_MESSAGE';
